name: user_feedback
description: A package for user feedback
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.1.1
  uuid: ^4.3.2

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/

flutter_gen:
  #  output: lib/gen/ # Optional (default: lib/gen/)
  #  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
  fonts:
    enabled: true